In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

In [20]:
from sklearn.datasets import load_iris

In [8]:
data = datasets.load_iris()

In [12]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
 X = normalize(data.data)

In [21]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
from sklearn.preprocessing import Normalizer

In [23]:
transformer = Normalizer().fit(data.data)

In [25]:
X1 = data.data

In [29]:
X1[0]

array([5.1, 3.5, 1.4, 0.2])

In [34]:
import math

In [43]:
X1.shape[0]

150

In [49]:
X2 = np.zeros((150,4))

In [50]:
X2.shape

(150, 4)

In [51]:
for i in range(X1.shape[0]):
    X2[i] = X1[i]/math.sqrt(sum(np.power(X1[i],2)))

In [54]:
X - X2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [52]:
XS = transformer.transform(data.data)

In [16]:
X

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [17]:
 y = data.target

In [55]:
np.random.seed(123)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [56]:
idx = np.arange(X.shape[0])

In [58]:
np.random.shuffle(idx)

In [59]:
idx

array([ 72, 112, 132,  88,  37, 138,  87,  42,   8,  90, 141,  33,  59,
       116, 135, 104,  36,  13,  63,  45,  28, 133,  24, 127,  46,  20,
        31, 121, 117,   4, 130, 119,  29,   0,  62,  93, 131,   5,  16,
        82,  60,  35, 143, 145, 142, 114, 136,  53,  19,  38, 110,  23,
         9,  86,  91,  89,  79, 101,  65, 115,  41, 124,  95,  21,  11,
       103,  74, 122, 118,  44,  51,  81, 149,  12, 129,  56,  50,  25,
       128, 146,  43,   1,  71,  54, 100,  14,   6,  80,  26,  70, 139,
        30, 108,  15,  18,  77,  22,  10,  58, 107,  75,  64,  69,   3,
        40,  76, 134,  34,  27,  94,  85,  97, 102,  52,  92,  99, 105,
         7,  48,  61, 120, 137, 125, 147,  39,  84,   2,  67,  55,  49,
        68, 140,  78, 144, 111,  32,  73,  47, 148, 113,  96,  57, 123,
       106,  83,  17,  98,  66, 126, 109])

In [76]:
idx.shape

(150,)

In [63]:
Xshuffle = X[idx]
Yshuffle = y[idx]

In [82]:
Yshuffle = Yshuffle.reshape(-1,1)

In [80]:
Xshuffle.shape

(150, 4)

In [61]:
X[72]

array([0.74143307, 0.29421947, 0.57667016, 0.17653168])

In [64]:
y[72]

1

In [65]:
Xtrain, Xtest = Xshuffle[:100], Xshuffle[100:]

In [67]:
Xtrain.shape

(100, 4)

In [68]:
Xtest.shape

(50, 4)

In [83]:
ytrain, ytest = Yshuffle[:100], Yshuffle[100:]

In [84]:
ytrain.shape

(100, 1)

In [86]:
ytest.shape

(50, 1)

In [77]:
ytrain

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 2,
       1, 2, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1,
       0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2])

In [78]:
y_test

array([1, 0, 1, 1, 1, 0, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 2, 2, 1, 2, 0,
       0, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 0, 0, 1, 2, 1, 2, 0,
       0, 1, 2, 2, 0])

In [87]:
k = 5

In [89]:
Xtrain.shape

(100, 4)

In [96]:
y_pred = np.empty(Xtest.shape[0])

In [97]:
y_pred.shape

(50,)

In [98]:
y_pred =  y_pred.reshape(-1,1)

In [99]:
y_pred.shape

(50, 1)

In [100]:
Xtest[0]

array([0.76785726, 0.34902603, 0.51190484, 0.16287881])

In [101]:
ytest[0]

array([1])

In [102]:
Xtrain[0]

array([0.74143307, 0.29421947, 0.57667016, 0.17653168])

In [103]:
ytrain[0]

array([1])

In [112]:
distance = np.empty((100,1))

In [129]:
for i in range(100):
    distance[i] = np.power(np.sum(np.power(Xtest[0] - Xtrain[i], 2)), 0.5)
    

In [130]:
distance1 = np.argsort(distance,0)

In [133]:
distance[66], distance[82]

(array([0.00803339]), array([0.00862486]))

In [136]:
smallDisInd = distance1[:k]

In [137]:
smallDisInd

array([[66],
       [82],
       [39],
       [58],
       [76]], dtype=int64)

In [138]:
Xtrain[smallDisInd]

array([[[0.76741698, 0.34773582, 0.51560829, 0.15588157]],

       [[0.77011854, 0.35349703, 0.50499576, 0.16412362]],

       [[0.76434981, 0.35581802, 0.51395936, 0.15814134]],

       [[0.76945444, 0.35601624, 0.50531337, 0.16078153]],

       [[0.76701103, 0.35063361, 0.51499312, 0.15340221]]])

In [145]:
ytrain[smallDisInd].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [148]:
np.bincount(ytrain[smallDisInd].reshape(-1).astype('int')).argmax()

1

In [149]:
ytest[0]

array([1])

In [ ]:
for i, test_sample in enumerate(X_test):
            # Sort the training samples by their distance to the test sample and get the K nearest
            idx = np.argsort([euclidean_distance(test_sample, x) for x in X_train])[:self.k]
            # Extract the labels of the K nearest neighboring training samples
            k_nearest_neighbors = np.array([y_train[i] for i in idx])
            # Label sample as the most common class label
            y_pred[i] = self._vote(k_nearest_neighbors)